### ISSUE TITLE
request | intro/outro background music

### ISSUE THREAD

**Issue by alejojo** [vmware-tanzu/thepodlets#101]
Hi there,

thank you for the podcasts, I really enjoy them!

about the subject, do you guys think it would be possible to change or at least lower the volume of the intro/outro?

cc: @carlisia

Cheers,

**Comment by carlisia** [comment]
Thanks for the feedback. We did lower the volume after a few episodes, but I don't remember what episode number was the first to have the lower into. If you listen to one of the last ones the volume should be ok, let me know if this is not the case.
