### ISSUE TITLE
The Renaissance of Event-Driven Architectures

### ISSUE THREAD

**Issue by embano1** [vmware-tanzu/thepodlets#40]
Talk about what event-driven architectures are, where they're used (hardware, kernels/OS, distributed systems), prominent examples such as AWS Lambda and OpenFaaS, the rise of event-streaming (Kafka, Beam/Dataflow) and why you might consider this architecture over "typical" request/response, e.g. REST/gRPC.

**Comment by bryanl** [comment]
Potential topics include:
* eventing and streaming as provided by knative
* what kinds of problems that are solved with eventing and streaming
