### ISSUE TITLE
020 - Kubernetes Operating Systems

### ISSUE THREAD

**Issue by andrewrynhard** [vmware-tanzu/thepodlets#58]
I just wanted to throw an idea out there for an episode. There is a good article out there that can explain this topic better than I, so I will point you to that for a little bit of background on the topic and why it is important: https://kubedex.com/kubernetes-operating-systems/

The TL;DR is that there are Kubernetes specific operating systems popping up, with companies working on building their own: https://twitter.com/chuhnk/status/1197583810109591552.

I think this would make for an interesting episode. Full disclosure, I am a  co-founder of Talos Systems, and I am working on an operating system for Kubernetes. The general idea though (a Kubernetes OS), is one that I find a lot of people in the community are interested in.

**Comment by carlisia** [comment]
Hi @andrewrynhard thank you for the suggestion. Yes, I think it's a great topic for this show to explore. Hang tight, I'll get back to schedule a date, might be slow to get back though, thanks for the patience.

**Comment by carlisia** [comment]
More references: 
https://www.youtube.com/watch?v=B_Zb9_Ralb4
https://lwn.net/SubscriberLink/806230/24ecb59c0d2c1f35/

**Comment by carlisia** [comment]
c/c @embano1

**Comment by carlisia** [comment]
Hey @andrewrynhard, would you be available to record a show this Wed, 9:50AM PT?

**Comment by andrewrynhard** [comment]
Hi @carlisia works for me!

**Comment by carlisia** [comment]
Cool. I'll send you a calendar invite at some point today!

**Comment by carlisia** [comment]
Hackmd:

https://hackmd.io/_czk4gOjTPW9-6ImelAHdg?both
