### ISSUE TITLE
017 - How to keep up with cloud native

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/thepodlets#75]
- what does up to date mean
- mention other podcasts and resources, twitter accounts

Audiences:
- ppl keeping up with the code base
- ppl keeping up with new features

**Comment by carlisia** [comment]
@mauilion, is this different from https://github.com/vmware-tanzu/thepodlets/issues/33?

**Comment by mauilion** [comment]
yes I think it is different

**Comment by embano1** [comment]
HackMD: https://hackmd.io/gz2hzic0TmSh03yiaDdegQ?both
