### ISSUE TITLE
018 - Should I Kubernetes?

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/thepodlets#77]
Building on https://github.com/vmware-tanzu/thepodlets/issues/13, an episode around **Is Kubernetes Right for You** is aptly timed.

As Kubernetes has popularized, it has gained a fair share of promoters and detractors. Many organizations and humans are wondering whether adopting Kubernetes is right for them. Namely, is it aligned with solving the problems they need to solve?

References:

* https://endler.dev/2019/maybe-you-dont-need-kubernetes/
* https://www.arp242.net/dont-need-k8s.html
* https://scalarsoftware.com/blog/why-most-companies-dont-need-kubernetes/
* https://github.blog/2017-08-16-kubernetes-at-github/
* https://techbeacon.com/devops/one-year-using-kubernetes-production-lessons-learned

**Comment by mauilion** [comment]
nice one!

**Comment by joshrosso** [comment]
Hackmd: https://hackmd.io/KCAifAt3T7evXVdF7dgw5Q
