### ISSUE TITLE
019 - Application Transformation - do I need to?

### ISSUE THREAD

**Issue by opowbow** [vmware-tanzu/thepodlets#79]
And if I need to ..what do I need to do ...??
what does that even mean
Address the spectrum 
does everything need to be transformed - do I need an AppTX
is it the right thing..? for everyone or everything
but why...??
Bringing our experience to where companies are with this

**Comment by carlisia** [comment]
https://content.pivotal.io/slides/application-transformation-workshop

**Comment by joshrosso** [comment]
Somethings we need to consider for the episode.

* Overview of how Pivotal/VMware thinks about Application Transformation.

* Addressing the spectrum of applications needs.
  * Rehost?
  * Replatform?
  * Transform / Modernize / etc
  * What does these mean and why would I do one?

* Why would someone modernize an application?

**Comment by joshrosso** [comment]
https://hackmd.io/-22AohucRL6N-VHZTXAtHQ

**Comment by carlisia** [comment]
# Episode 19: Application Modernization

### Tagline: 



---
## VIDEO

### Please make sure this setting is on!
![](https://i.imgur.com/Ud771Hx.png)

---
### Hosts

* Olive Power
* Carlisia Campos (lead today)
* Duffie Cooley
* Josh Rosso

### Guests
* Shaun Anderson = @swiftbird68
* Chris Umbel

---
## Topic
!!!NOTE: BE SURE TO START RECORDING!!!

### 1. Introduction

* Welcome to the Podlets Podcast!
* Today's topic, Application Modernization.

### 2. Context

* What does "Applicaiton Modernization" mean to us?
* How is this diferent from digital transformation?
* Why do companies considering modernization work?
* How do we approach modernizing legacy applications?


### 3. Types of Transformation
* What is considered legacy these days?
* There are a few 'flavors' of things people do with their legacy applications.
    * Nothing
    * Rehost
    * Replatform
    * Rearchitect / Reimplement
* Are the above different?
    * If so, how do you discern them?
* How do you assess what an application needs?

### 4. Modernizing Infrastructure and Applications

* Over the years, we've seen infrastrcture modernization drive the need for app modernization.
    * e.g. you need to be a 12 factor app, running ha, stateless, or simply, "you need to move to the cloud".
* Is this a healthy forcing function?
* Should companies be going app first? infra first? or both?
    * The concerns of app and infra teams can often feel very unaligned.

## Show notes

## References

* Pivotal Presentation on Application Transformation: https://content.pivotal.io/slides/application-transformation-workshop
* Alberto Brandolini 'Event Storming' book: https://www.eventstorming.com/book
* Swift Methodology: https://swiftbird.us





---
Closing blurb

Send us your concepts and ideas in the github issue tracker. 

See existing episode suggestions and add your own: https://github.com/vmware-tanzu/thepodlets/issues
